name: Lint

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  type-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Init python poetry action
        uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Lint with mypy
        run: |
          poetry run mypy pyzeebe

  import-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Init python poetry action
        uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Check imports
        run: |
          poetry run isort . --check --diff

  format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Init python poetry action
        uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Check imports
        run: |
          poetry run black --check .
