name: Test pyzeebe

on: [push, pull_request]

jobs:
  # 3.6, 3.7 and 3.8 only for passing branch rules
  # https://github.com/camunda-community-hub/pyzeebe/issues/381#issuecomment-2107430780
  unit-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
        if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' && matrix.python-version != '3.8' }}
      - name: Init python poetry action
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3
        if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' && matrix.python-version != '3.8' }}
      - name: Install dependencies
        run: poetry install
        if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' && matrix.python-version != '3.8' }}
      - name: Test with pytest
        run: |
          poetry run coverage run --source=pyzeebe -m pytest tests/unit
        if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' && matrix.python-version != '3.8' }}
      - name: Upload to coveralls
        run: |
          poetry run coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ matrix.python-version != '3.6' && matrix.python-version != '3.7' && matrix.python-version != '3.8' }}

  integration-test:
    env:
      ZEEBE_ADDRESS: "zeebe:26500"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        zeebe-version: ["8.2.29", "8.3.13", "8.4.9", "8.5.5"]

    services:
      zeebe:
        image: camunda/zeebe:${{ matrix.zeebe-version }}
        ports:
          - 26500/tcp

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Init python poetry action
        uses: abatilo/actions-poetry@v3.0.0
        with:
          poetry-version: 1.8.3
      - name: Install dependencies
        run: poetry install
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"

      - name: Run integration tests
        run: |
          poetry run pytest tests/integration
